### ISSUE TITLE
CHORE: FE 프로젝트 초기 설정하기

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#1]
## 이슈 요약

frontend 애플리케이션을 위한 최소한의 설정을 구성하여 앞으로의 기능 개발을 진행할 수 있어야 한다.

<br>

## TODO

- [x] create-react-app with typescript template, 불필요 파일 제거
- [x] `eslint` & `prettier` 설정하기
- [x] typescript type-alias 설정하기

<br>

**Comment by pds0309** [comment]
abc

**Comment by pds0309** [comment]
@heayounchoi hi

**Comment by pds0309** [comment]
@pds0309 뿌쉬알람테슈튜
