### ISSUE TITLE
FEAT: 수정 디자인 및 새로운 디자인 UI 반영

### ISSUE THREAD

**Issue by heayounchoi** [gachimind/frontend#106]
## 이슈 요약

수정 디자인 및 새로운 디자인 UI 반영

<br>

## TODO

- [x] 닉네임/캐릭터 설정 모달
- [x] 가입 완료 모달
- [ ] 마이페이지/로그아웃 모달
- [ ] 회원탈퇴 안내 모달
- [ ] 메인페이지 디자인 변경
- [ ] 마이페이지 디자인 반영
- [ ] 마우스 커서

**Comment by pds0309** [comment]
@heayounchoi 
어떤 부분들 작업하시는지 간단하게 명시해주시면 감사하겠습니당! 👍👍👍

**Comment by heayounchoi** [comment]
@pds0309 디자인 변경이 좀 많은 것 같은데 동석님도 피그마 한번 보셔야겠어여ㅎㅎ,, 게임 결과 모달에 고양이 다 올라가네여

**Comment by pds0309** [comment]
> @pds0309 디자인 변경이 좀 많은 것 같은데 동석님도 피그마 한번 보셔야겠어여ㅎㅎ,, 게임 결과 모달에 고양이 다 올라가고 레디/스타트 버튼 모달로 바뀐것같네요

변경된 모든 걸 이 이슈에서 다 하시진 않을테니 어느 부분을 하실지 여쭤본겁니다! 작성하신걸 보니 당장 저랑 겹치진 않겠네요

**Comment by heayounchoi** [comment]
@pds0309 아 한번에 하려고 했는데 혹시 동석님 어디 작업하시게여??

**Comment by pds0309** [comment]
아 댓글단다는걸 모르고 혜연님 댓글을 수정해버렸네요 ㅋㅋㅋㅋㅋ 죄송합니다 😢

**Comment by pds0309** [comment]
@heayounchoi 

로딩페이지는 제가 따로 이슈파서 작업하겠습니다 👍
