### ISSUE TITLE
FEAT: 게임 페이지 스코어보드 구성하기

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#110]
## 이슈 요약

게임 페이지 스코어보드를 구성한다.

<br>

## TODO

- [x] 배경 UI가 있다.
- [X] 머리위에 띄울 점수 라벨 UI가 있다.
- [X] 그 위에 닉네임이 배치될 닉네임 UI가 있다.
- [x] 고양이들을 보드에 배치할 수 있다.
- [x] 고양이는 사용자가 레디하면 로켓을 탄다.
- [x] 고양이들은 얻은 점수에 맞춰 그만큼 위로 움직인다.
- [X] 결과 모달에 고양이 배치하기

<br>
