### ISSUE TITLE
FEAT: 게임 종료 시 스코어 관련 처리 추가하기

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#116]
## 이슈 요약

- 게임 페이지 스코어에 대해 게임 종료 이벤트를 적절하게 적용한다.

<br>

## TODO

- [x] 게임 종료시에도 결과 모달의 사용자 정보가 나와야 한다.
- [x] 스코어 보드 고양이 머리위의 스코어가 결과 모달을 닫으면 초기화 되어야 한다.
- [x] 스코어 보드 고양이의 높이가 결과 모달을 닫으면 초기화 되어야 한다.
- [x] 게임 종료 시 모든 플레이어의 ready 상태는 초기화되고 게임방 상태는 '대기'가 되어야 한다.
- [x] 게임 종료 또는 게임 도중 플레이어가 방을 이탈 할 경우 이전 게임방 관련 상태는 모두 삭제되어야 한다.

<br>
