### ISSUE TITLE
FEAT: 게임방 상태를 분리하고 소켓 통신을 적용

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#13]
## 이슈 요약

최소한의 방 생성/입장/퇴장 흐름 외의 서비스에서 지정된 게임방 상태 흐름 처리가 필요하다.

<br>

## TODO

- [x] 게임방은 `대기`/`게임 진행중` 상태를 가진다.
~~사용자는 `게임 대기`/`게임 중`/게임 종료` 상태를 가진다.~~
- [x] 대기 상태의 게임방에서 방장이 아닌 사용자들은 `ready`를 할 수 있다. (소켓으로 넘긴다.)
- [x] 방장은 모두가 레디했을 때 게임방을 `게임 진행중` 상태로 변경시킬 수 있다.

<br>

## 미래의 우리를 위한 메모

- 게임 진행 상태에서 게임에 대한 상세 로직을 구성해야 한다.
