### ISSUE TITLE
FEAT: 방 입장/생성 기능을 구체화 

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#14]
## 이슈 요약

최소화 되어있는 방 입장, 방 생성 기능을 구체화

<br>

## TODO

- [ ] 방이 꽉 차면 사용자가 더 이상 들어갈 수 없다.
- [ ] `진행중` 상태일 경우 방에 입장할 수 없다.
- [ ] 방 생성 폼 모달 내용을 기획에 맞춰 모두 적용하고 유효성 검증을 할 수 있다.
- [ ] 비밀 방일 경우 입장 시 비밀번호를 입력받아 일치 할 경우에만 입장이 가능하다.

<br>

## 의존 이슈

- #13
