### ISSUE TITLE
FEAT: 탈주자 처리

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#145]
## 이슈 요약

게임 도중 탈주 했을 때에 대한 상황을 고려하여 기능을 추가하자

<br>

## TODO(체크리스트)

- [x] 게임 도중 사람이 나가 혼자 남았을 때 초기 상태로 돌아오는가
- [x] 게임 도중 발표자가 아닌 사람이 나갔을 때도 게임이 문제 없이 흐르는가
- [ ] 게임 도중 발표자가 나갔을 때 다음 사람으로 잘 넘어가는가

<br>
