### ISSUE TITLE
FIX: 자잘한 UI 수정/추가

### ISSUE THREAD

**Issue by heayounchoi** [gachimind/frontend#146]
## 이슈 요약

자잘한 UI를 수정 및 추가한다.

<br>

## TODO

- [x] 커서 크기 줄이기
- [x] 모달 clickaway 로그아웃 모달 외 안되도록 수정
- [x] 버튼 이벤트 디자인 Button 컴포넌트에만 적용되도록 수정
- [x] 콘솔에 찍히던 이미지 에러 해결
- [x] 메인/마이페이지 footer에 인스타그램 연결 버튼 추가
- [x] favicon/meta description 수정
