### ISSUE TITLE
FIX: 스코어링 관련 문제 해결하기

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#165]
## 이슈 요약

스코어링이 정상적으로 되지 않는 부분을 해결

<br>

## TODO

- [ ] ~~발표자가 평가를 받는데 다른 사람이 점수를 받는 문제~~
- [x] 점수가 의도와 다르게 비정상적으로 오르는 문제
- [ ] ~~1턴 이후부터 처리가 안되며 방장에게 몰아지는 문제 발생됨~~

<br>
