### ISSUE TITLE
FEAT: json server 업데이트

### ISSUE THREAD

**Issue by heayounchoi** [gachimind/frontend#187]
## 이슈 요약

추가 및 수정된 api를 json server에 업데이트 한다.

<br>

## TODO

- [x] 구글 소셜 로그인 삭제
- [x] 닉네임 중복확인 수정
- [x] 회원정보 수정 추가
- [x] 버그 리포트 추가
- [x] 최초 로그인 식별 추가
