### ISSUE TITLE
BUILD: Route53-CloudFront-S3-GithubActions CI/CD 구현

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#22]
## 이슈 요약

Githubactions - S3 - CloudFront - Route53으로 main 브랜치 CI/CD를 구현하라

<br>

## TODO

- [x] github-actions 워크 플로우 코드를 작성하라
- [x] 깃허브 리포지토리 secret에 환경값들을 넣어라
- [x] S3 버킷을 만들고 정적호스팅 설정을 하라
- [x] 도메인을 만들어라
- [x] CloudFront 설정을 하고 연결하라

<br>

## 버셀 내두고 왜 힘들게?

![image](https://user-images.githubusercontent.com/76927397/212470381-b650168b-c9cf-4cb6-b075-0b1d5c63c73b.png)

어려운 말이 있어서

<br>

## 필수적으로 인지해야하는 것들

- `.env`의 환경변수 값 자체가 수정된다면 `main`브랜치로 릴리즈하기 전에 반드시 `github repository secret`에서 그 값을 변경해야 한다.

- 새로운 환경변수가 추가되면 워크플로우에도 반영해야 한다

<br>

## [정리 블로그](https://velog.io/@pds0309/Day37-Github-actions-S3-CloudFront-Route53%EC%9C%BC%EB%A1%9C-React-CICD%ED%95%98%EA%B8%B0)
