### ISSUE TITLE
FEAT: 게임 진행 시 키워드 힌트 보여주기 

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#231]
## 이슈 요약

게임 진행 시 키워드 힌트를 보여줄 수 있다.

<br>

## TODO

- [x] 키워드 이벤트 아이콘 및 말풍선 UI 구성
- [x] 발표자가 준비 시간에 힌트를 확인할 수 있다.
- [X] 토론 시간에 모두가 힌트를 확인할 수 있다.
