### ISSUE TITLE
FEAT: 와이어프레임 기반 모달 UI 구현

### ISSUE THREAD

**Issue by heayounchoi** [gachimind/frontend#33]
## 이슈 요약

와이어프레임 기반 모달 UI 구현

<br>

## TODO

- [x] 로그인/방 생성 모달 UI 수정
- [x] 방 참가하기/닉네임 변경/버그 제보 모달 생성
- [x] 게임 규칙/게임 결과 모달 생성

<br>

## 참고사항

- 캐릭터 설정 모달은 아직 와이어프레임 작업 진행중으로 완료시 진행
