### ISSUE TITLE
FIX: 메인 페이지, 게임 페이지 UI 수정 및 누락 디자인 추가

### ISSUE THREAD

**Issue by heayounchoi** [gachimind/frontend#54]
## 이슈 요약

중간 발표를 위해 급하게 작성한 코드 수정 및 누락 디자인 추가

<br>

## TODO

- [x] 누락 폰트 추가
- [x] 불필요 코드 삭제
- [x] 누락 디자인 디테일 추가
- [x] 오타/컨벤션 안지킨 코드들 수정
- [x] 메인페이지 깜빡임 현상 해결

**Comment by pds0309** [comment]
공통컴포넌트 분리는 이슈 하나 더 빼도될것같아요 양이 만흘것같네요 👍
