### ISSUE TITLE
FEAT: 게임만들기 입력 제한/글자 수 잘리는 부분 애니메이션 추가

### ISSUE THREAD

**Issue by heayounchoi** [gachimind/frontend#77]
## 이슈 요약

게임만들기 입력 제한/글자 수 잘리는 부분 애니메이션 추가

<br>

## TODO

- [x] 게임 페이지 참여자 캠 status 닉네임/메인 페이지 유저 섹션 닉네임 일정 길이 넘어가면 흘러다니게 만들기
- [x] 방제 12자 길이 제한, 일정 길이 넘어가면 흘러가게 만들기(기본 방제: 가치마인드 한 판 해요)
- [x] 비밀번호 숫자 4자리 게임방 만들기 모달에 제한 두기
- [x] 비밀번호 없이도 방 만들 수 있게 해놓기
- [x] 카운트 선택지 2개 셀렉트로 수정하기
