### ISSUE TITLE
FEAT: socket 통신을 통한 GameRoom 생성/입장/퇴장 주기에 대한 기능을 구현

### ISSUE THREAD

**Issue by pds0309** [gachimind/frontend#8]
## 이슈 요약

소켓 통신 설정을 구성하고 GameRoom 생성/입장/퇴장 흐름을 구성해야 한다.

<br>

## TODO

- [x] 클라이언트에서 서버와 socket 통신을 할 수 있도록 설정한다.
- [x] 사용자는 게임 방을 생성할 수 있으며 생성 성공 시 즉시 입장된다.
- [x] 게임방의 사용자들은 게임방 상태 변화 정보를 실시간으로 제공받을 수 있다.(인원 출입, 방장변경)
- [x] 생성된 방들의 상태는 실시간으로 메인 route에 보여진다.
- [x] 사용자는 방을 입장할 수 있다.
- [x] 사용자는 방에서 나갈 수 있다.
- [x] 게임방과 관련된 모든 소켓통신 정보는 실시간으로 갱신될 수 있다.

<br>

## 특이사항

- UI 구성을 최소화 하여 기능 동작 여부에 초점을 두고 진행한다.
- 인증된 사용자만 할 수 있는 행위임을 배제하고 진행한다.
- ~~작업 내용이 많을 것 같아 리뷰하실 혜연님이 힘들 것이라는 생각을 하니 마음이 아프다~~

<br>

## 미래의 우리를 위한 메모

- 예외처리 로직이 추가되어야 한다.
- 사용자 인증 흐름이 구현될 경우 반영해야 한다.

**Comment by heayounchoi** [comment]
@pds0309 리뷰 재밌네용 ㄷㄷㄷㄷ 기대가 됩니다
