### ISSUE TITLE
FEAT: 추가된 디자인 UI 반영

### ISSUE THREAD

**Issue by heayounchoi** [gachimind/frontend#82]
## 이슈 요약

추가된 디자인 UI 반영

<br>

## TODO

- [x] 스코어 모달 디자인 반영
- [x] 버그제보 모달 디자인 반영
- [x] 닉네임 변경 모달 디자인 반영
- [x] 키워드 박스 디자인 반영
- [ ] 모달 컴포넌트 수정
